def run_cli(argv: list[str]) -> None: ...
def new_document(name: str) -> str: ...
def load_document(path: str) -> str: ...
def save_document(json: str, path: str) -> None: ...
def export_svg(json: str) -> str: ...
